/**
 * Generated by `scripts/docs-sync.mjs`.
 * Do not edit manually.
 */
export const externalDocsNav = [
  {
    "name": "Agent",
    "package": "agent",
    "pages": [
      {
        "title": "Agents",
        "url": "/docs/packages/agent"
      },
      {
        "title": "Quickstart",
        "url": "/docs/packages/agent/quickstart"
      },
      {
        "title": "Agent machines",
        "url": "/docs/packages/agent/machines"
      },
      {
        "title": "Decisions",
        "url": "/docs/packages/agent/decisions"
      },
      {
        "title": "Text requests",
        "url": "/docs/packages/agent/text-requests"
      },
      {
        "title": "Messages",
        "url": "/docs/packages/agent/messages"
      },
      {
        "title": "Context compaction",
        "url": "/docs/packages/agent/context-compaction"
      },
      {
        "title": "Human in the loop",
        "url": "/docs/packages/agent/human-in-the-loop"
      },
      {
        "title": "Hosts and executors",
        "url": "/docs/packages/agent/hosts"
      },
      {
        "title": "Using with other stacks",
        "url": "/docs/packages/agent/interop"
      },
      {
        "title": "The step path",
        "url": "/docs/packages/agent/steps"
      },
      {
        "title": "Machines as data",
        "url": "/docs/packages/agent/machines-as-data"
      },
      {
        "title": "Multi-agent composition",
        "url": "/docs/packages/agent/multi-agent"
      },
      {
        "title": "Examples",
        "url": "/docs/packages/agent/examples"
      },
      {
        "title": "Post-alpha roadmap",
        "url": "/docs/packages/agent/roadmap"
      }
    ]
  },
  {
    "name": "Graph",
    "package": "graph",
    "pages": [
      {
        "title": "@statelyai/graph",
        "url": "/docs/packages/graph"
      },
      {
        "title": "Algorithms reference",
        "url": "/docs/packages/graph/algorithms"
      },
      {
        "title": "Layout",
        "url": "/docs/packages/graph/layout"
      },
      {
        "title": "React Flow + ELK: automatic layout cookbook",
        "url": "/docs/packages/graph/react-flow-elk-pipeline"
      },
      {
        "title": "Layout transitions",
        "url": "/docs/packages/graph/layout-transitions"
      },
      {
        "title": "Migrating from @dagrejs/graphlib",
        "url": "/docs/packages/graph/migrating-from-graphlib"
      },
      {
        "title": "Benchmarks",
        "url": "/docs/packages/graph/benchmarks"
      },
      {
        "title": "Scaling & Plugin Architecture",
        "url": "/docs/packages/graph/scaling-and-plugins"
      }
    ]
  },
  {
    "name": "SDK",
    "package": "sdk",
    "pages": [
      {
        "title": "@statelyai/sdk",
        "url": "/docs/packages/sdk"
      }
    ]
  },
  {
    "name": "CLI",
    "package": "cli",
    "pages": [
      {
        "title": "statelyai",
        "url": "/docs/packages/cli"
      }
    ]
  },
  {
    "name": "MCP",
    "package": "mcp",
    "pages": [
      {
        "title": "Stately MCP",
        "url": "/docs/packages/mcp"
      }
    ]
  }
] as const;
