/**
 * Generated by `scripts/docs-sync.mjs`.
 * Do not edit manually.
 */
import { docs as graphDocs } from 'collections/graph/server';


export const externalDocsCollections = {
  graph: graphDocs,
} as const;
