/**
 * Generated by `scripts/docs-sync.mjs`.
 * Do not edit manually.
 */
export const externalDocsNav = [
  {
    "name": "Agent",
    "package": "agent",
    "pages": [
      {
        "separator": true,
        "title": "Get started"
      },
      {
        "title": "Agents",
        "url": "/docs/packages/agent"
      },
      {
        "title": "Quickstart",
        "url": "/docs/packages/agent/quickstart"
      },
      {
        "title": "Thinking in state machines",
        "url": "/docs/packages/agent/thinking-in-state-machines"
      },
      {
        "title": "Migrating from a hand-rolled loop",
        "url": "/docs/packages/agent/from-a-loop"
      },
      {
        "title": "Scope and ecosystem boundaries",
        "url": "/docs/packages/agent/scope"
      },
      {
        "separator": true,
        "title": "Core concepts"
      },
      {
        "title": "Agent machines",
        "url": "/docs/packages/agent/machines"
      },
      {
        "title": "Decisions",
        "url": "/docs/packages/agent/decisions"
      },
      {
        "title": "Text requests",
        "url": "/docs/packages/agent/text-requests"
      },
      {
        "title": "Tools",
        "url": "/docs/packages/agent/tools"
      },
      {
        "title": "Messages",
        "url": "/docs/packages/agent/messages"
      },
      {
        "title": "Preset machines",
        "url": "/docs/packages/agent/machines-presets"
      },
      {
        "separator": true,
        "title": "Running agents"
      },
      {
        "title": "Choosing a run mode",
        "url": "/docs/packages/agent/choosing-a-run-mode"
      },
      {
        "title": "Hosts and executors",
        "url": "/docs/packages/agent/hosts"
      },
      {
        "title": "Use in any stack",
        "url": "/docs/packages/agent/any-stack"
      },
      {
        "title": "The step path",
        "url": "/docs/packages/agent/steps"
      },
      {
        "separator": true,
        "title": "State & durability"
      },
      {
        "title": "Where state lives",
        "url": "/docs/packages/agent/persistence"
      },
      {
        "title": "The event log",
        "url": "/docs/packages/agent/event-log"
      },
      {
        "title": "Human in the loop",
        "url": "/docs/packages/agent/human-in-the-loop"
      },
      {
        "separator": true,
        "title": "Production"
      },
      {
        "title": "Models and providers",
        "url": "/docs/packages/agent/models-and-providers"
      },
      {
        "title": "Observability",
        "url": "/docs/packages/agent/observability"
      },
      {
        "title": "Usage and budgets",
        "url": "/docs/packages/agent/usage-and-budgets"
      },
      {
        "title": "Debugging",
        "url": "/docs/packages/agent/debugging"
      },
      {
        "title": "Multi-agent composition",
        "url": "/docs/packages/agent/multi-agent"
      },
      {
        "separator": true,
        "title": "Machines as data"
      },
      {
        "title": "Machines as data",
        "url": "/docs/packages/agent/machines-as-data"
      },
      {
        "title": "Generating machines with an LLM",
        "url": "/docs/packages/agent/generate-machines"
      },
      {
        "separator": true,
        "title": "Testing"
      },
      {
        "title": "Testing and verification",
        "url": "/docs/packages/agent/verify"
      },
      {
        "title": "Evals",
        "url": "/docs/packages/agent/evals"
      },
      {
        "separator": true,
        "title": "Resources"
      },
      {
        "title": "Agent patterns",
        "url": "/docs/packages/agent/patterns"
      },
      {
        "title": "Coming from LangGraph",
        "url": "/docs/packages/agent/langgraph-comparison"
      },
      {
        "title": "Post-alpha roadmap",
        "url": "/docs/packages/agent/roadmap"
      }
    ],
    "route": "packages/agent"
  },
  {
    "name": "Graph",
    "package": "graph",
    "pages": [
      {
        "title": "@statelyai/graph",
        "url": "/docs/packages/graph"
      },
      {
        "title": "Algorithms reference",
        "url": "/docs/packages/graph/algorithms"
      },
      {
        "title": "Benchmarks",
        "url": "/docs/packages/graph/benchmarks"
      },
      {
        "title": "Layout",
        "url": "/docs/packages/graph/layout"
      },
      {
        "title": "Layout transitions",
        "url": "/docs/packages/graph/layout-transitions"
      },
      {
        "title": "Migrating from @dagrejs/graphlib",
        "url": "/docs/packages/graph/migrating-from-graphlib"
      },
      {
        "title": "React Flow + ELK: automatic layout cookbook",
        "url": "/docs/packages/graph/react-flow-elk-pipeline"
      },
      {
        "title": "Scaling & Plugin Architecture",
        "url": "/docs/packages/graph/scaling-and-plugins"
      }
    ],
    "route": "packages/graph"
  },
  {
    "name": "XState v6 alpha",
    "package": "xstate-v6",
    "pages": [
      {
        "separator": true,
        "title": "Start"
      },
      {
        "title": "Quick start",
        "url": "/docs/xstate/v6/quick-start"
      },
      {
        "title": "Choose XState",
        "url": "/docs/xstate/v6/choose-xstate"
      },
      {
        "title": "Use with your framework",
        "url": "/docs/xstate/v6/frameworks"
      },
      {
        "title": "Examples",
        "url": "/docs/xstate/v6/examples"
      },
      {
        "separator": true,
        "title": "Learn"
      },
      {
        "title": "Why state machines?",
        "url": "/docs/xstate/v6/why-state-machines"
      },
      {
        "title": "Your first machine",
        "url": "/docs/xstate/v6/your-first-machine"
      },
      {
        "title": "Tutorial: build a media player",
        "url": "/docs/xstate/v6/tutorial"
      },
      {
        "title": "States, events and transitions",
        "url": "/docs/xstate/v6/states-events-transitions"
      },
      {
        "title": "Data and effects",
        "url": "/docs/xstate/v6/data-and-effects"
      },
      {
        "title": "Async logic",
        "url": "/docs/xstate/v6/async-logic"
      },
      {
        "title": "Actors",
        "url": "/docs/xstate/v6/actors"
      },
      {
        "title": "Statecharts",
        "url": "/docs/xstate/v6/statecharts"
      },
      {
        "title": "How XState runs your machine",
        "url": "/docs/xstate/v6/how-xstate-runs-machines"
      },
      {
        "title": "Model application behavior",
        "url": "/docs/xstate/v6/modeling"
      },
      {
        "separator": true,
        "title": "Build"
      },
      {
        "title": "Handle async requests",
        "url": "/docs/xstate/v6/async-requests"
      },
      {
        "title": "Add retries and timeouts",
        "url": "/docs/xstate/v6/retries-and-timeouts"
      },
      {
        "title": "Cancel async work",
        "url": "/docs/xstate/v6/cancellation"
      },
      {
        "title": "Build forms and wizards",
        "url": "/docs/xstate/v6/forms-and-wizards"
      },
      {
        "title": "Run backend workflows",
        "url": "/docs/xstate/v6/backend-workflows"
      },
      {
        "title": "Durable execution",
        "url": "/docs/xstate/v6/durable-execution"
      },
      {
        "title": "Persist and restore actors",
        "url": "/docs/xstate/v6/persist-and-restore-actors"
      },
      {
        "title": "Test XState logic",
        "url": "/docs/xstate/v6/testing"
      },
      {
        "title": "Inspect actor systems",
        "url": "/docs/xstate/v6/inspect-actor-systems"
      },
      {
        "title": "Troubleshooting",
        "url": "/docs/xstate/v6/troubleshooting"
      },
      {
        "separator": true,
        "title": "Machine reference"
      },
      {
        "title": "Machine configuration",
        "url": "/docs/xstate/v6/configuration"
      },
      {
        "title": "Setup and provide",
        "url": "/docs/xstate/v6/setup-and-provide"
      },
      {
        "title": "States",
        "url": "/docs/xstate/v6/states"
      },
      {
        "title": "Transitions",
        "url": "/docs/xstate/v6/transitions"
      },
      {
        "title": "Context",
        "url": "/docs/xstate/v6/context"
      },
      {
        "title": "Input and output",
        "url": "/docs/xstate/v6/input-output"
      },
      {
        "title": "State input",
        "url": "/docs/xstate/v6/state-input"
      },
      {
        "title": "Actions",
        "url": "/docs/xstate/v6/actions"
      },
      {
        "title": "Guards",
        "url": "/docs/xstate/v6/guards"
      },
      {
        "title": "Delays",
        "url": "/docs/xstate/v6/delays"
      },
      {
        "title": "Timeouts",
        "url": "/docs/xstate/v6/timeouts"
      },
      {
        "title": "Internal events",
        "url": "/docs/xstate/v6/internal-events"
      },
      {
        "title": "Choice states",
        "url": "/docs/xstate/v6/choice-states"
      },
      {
        "title": "Route states",
        "url": "/docs/xstate/v6/route-states"
      },
      {
        "title": "Final states",
        "url": "/docs/xstate/v6/final-states"
      },
      {
        "title": "History states",
        "url": "/docs/xstate/v6/history-states"
      },
      {
        "title": "Parallel states",
        "url": "/docs/xstate/v6/parallel-states"
      },
      {
        "separator": true,
        "title": "Actor reference"
      },
      {
        "title": "Create actors",
        "url": "/docs/xstate/v6/create-actor"
      },
      {
        "title": "Actor snapshots",
        "url": "/docs/xstate/v6/snapshots"
      },
      {
        "title": "Selectors",
        "url": "/docs/xstate/v6/selectors"
      },
      {
        "title": "Invoke actors",
        "url": "/docs/xstate/v6/invoke"
      },
      {
        "title": "Spawn actors",
        "url": "/docs/xstate/v6/spawn"
      },
      {
        "title": "Actor logic",
        "url": "/docs/xstate/v6/actor-logic"
      },
      {
        "title": "Emitted events",
        "url": "/docs/xstate/v6/emitted-events"
      },
      {
        "title": "Listen and subscribe to actors",
        "url": "/docs/xstate/v6/listen-and-subscribe"
      },
      {
        "title": "Actor systems",
        "url": "/docs/xstate/v6/systems"
      },
      {
        "title": "Lifecycle and errors",
        "url": "/docs/xstate/v6/lifecycle-and-errors"
      },
      {
        "separator": true,
        "title": "Reference"
      },
      {
        "title": "TypeScript",
        "url": "/docs/xstate/v6/typescript"
      },
      {
        "title": "Persistence",
        "url": "/docs/xstate/v6/persistence"
      },
      {
        "title": "Serialization",
        "url": "/docs/xstate/v6/serialization"
      },
      {
        "title": "Inspection",
        "url": "/docs/xstate/v6/inspection"
      },
      {
        "title": "Utilities",
        "url": "/docs/xstate/v6/utilities"
      },
      {
        "title": "Cheatsheet",
        "url": "/docs/xstate/v6/cheatsheet"
      },
      {
        "title": "Frequently asked questions",
        "url": "/docs/xstate/v6/faq"
      },
      {
        "title": "Glossary",
        "url": "/docs/xstate/v6/glossary"
      },
      {
        "separator": true,
        "title": "Migrate"
      },
      {
        "title": "Migrate from XState v5 to v6",
        "url": "/docs/xstate/v6/xstate-v5-to-v6"
      },
      {
        "separator": true,
        "title": "Contribute"
      },
      {
        "title": "Contributing documentation",
        "url": "/docs/xstate/v6/documentation"
      },
      {
        "separator": true,
        "title": "React"
      },
      {
        "title": "Use a machine in React",
        "url": "/docs/xstate/v6/react/use-machine"
      },
      {
        "title": "Select actor data",
        "url": "/docs/xstate/v6/react/selectors"
      },
      {
        "title": "Share actors",
        "url": "/docs/xstate/v6/react/shared-actors"
      },
      {
        "title": "Global state",
        "url": "/docs/xstate/v6/react/global-state"
      },
      {
        "title": "Input and restored snapshots",
        "url": "/docs/xstate/v6/react/input-and-snapshots"
      },
      {
        "title": "Server rendering",
        "url": "/docs/xstate/v6/react/server-rendering"
      },
      {
        "title": "Test React components",
        "url": "/docs/xstate/v6/react/testing"
      },
      {
        "separator": true,
        "title": "Vue"
      },
      {
        "title": "Use a machine in Vue",
        "url": "/docs/xstate/v6/vue/use-machine"
      },
      {
        "title": "Select actor data",
        "url": "/docs/xstate/v6/vue/selectors"
      },
      {
        "title": "Share actors",
        "url": "/docs/xstate/v6/vue/shared-actors"
      },
      {
        "title": "Input and restored snapshots",
        "url": "/docs/xstate/v6/vue/input-and-snapshots"
      },
      {
        "title": "Server rendering",
        "url": "/docs/xstate/v6/vue/server-rendering"
      },
      {
        "title": "Test Vue components with actors",
        "url": "/docs/xstate/v6/vue/testing"
      },
      {
        "separator": true,
        "title": "Svelte"
      },
      {
        "title": "Use a machine in Svelte",
        "url": "/docs/xstate/v6/svelte/use-machine"
      },
      {
        "title": "Select actor data",
        "url": "/docs/xstate/v6/svelte/selectors"
      },
      {
        "title": "Share actors",
        "url": "/docs/xstate/v6/svelte/shared-actors"
      },
      {
        "title": "Input and restored snapshots",
        "url": "/docs/xstate/v6/svelte/input-and-snapshots"
      },
      {
        "title": "Server rendering",
        "url": "/docs/xstate/v6/svelte/server-rendering"
      },
      {
        "title": "Test Svelte components with actors",
        "url": "/docs/xstate/v6/svelte/testing"
      },
      {
        "separator": true,
        "title": "Solid"
      },
      {
        "title": "Use a machine in Solid",
        "url": "/docs/xstate/v6/solid/use-machine"
      },
      {
        "title": "Select actor data",
        "url": "/docs/xstate/v6/solid/selectors"
      },
      {
        "title": "Share actors",
        "url": "/docs/xstate/v6/solid/shared-actors"
      },
      {
        "title": "Input and restored snapshots",
        "url": "/docs/xstate/v6/solid/input-and-snapshots"
      },
      {
        "title": "Server rendering",
        "url": "/docs/xstate/v6/solid/server-rendering"
      },
      {
        "title": "Test Solid components with actors",
        "url": "/docs/xstate/v6/solid/testing"
      },
      {
        "separator": true,
        "title": "Store"
      },
      {
        "title": "Quick start",
        "url": "/docs/xstate/v6/store/quick-start"
      },
      {
        "title": "Events and context",
        "url": "/docs/xstate/v6/store/events-and-context"
      },
      {
        "title": "Effects and emitted events",
        "url": "/docs/xstate/v6/store/effects-and-emitted-events"
      },
      {
        "title": "Selectors",
        "url": "/docs/xstate/v6/store/selectors"
      },
      {
        "title": "Framework bindings",
        "url": "/docs/xstate/v6/store/frameworks"
      },
      {
        "title": "Persistence",
        "url": "/docs/xstate/v6/store/persistence"
      },
      {
        "title": "Undo and redo",
        "url": "/docs/xstate/v6/store/undo-redo"
      },
      {
        "title": "TypeScript",
        "url": "/docs/xstate/v6/store/typescript"
      },
      {
        "title": "Migration",
        "url": "/docs/xstate/v6/store/migration"
      }
    ],
    "route": "xstate/v6"
  },
  {
    "name": "SDK",
    "package": "sdk",
    "pages": [
      {
        "title": "@statelyai/sdk",
        "url": "/docs/packages/sdk"
      }
    ],
    "route": "packages/sdk"
  },
  {
    "name": "CLI",
    "package": "cli",
    "pages": [
      {
        "title": "statelyai",
        "url": "/docs/packages/cli"
      }
    ],
    "route": "packages/cli"
  },
  {
    "name": "MCP",
    "package": "mcp",
    "pages": [
      {
        "title": "Stately MCP",
        "url": "/docs/packages/mcp"
      }
    ],
    "route": "packages/mcp"
  }
] as const;
