/**
 * Generated by `scripts/docs-sync.mjs`.
 * Do not edit manually.
 */
export const externalDocsNav = [
  {
    "name": "Graph",
    "package": "graph",
    "pages": [
      {
        "title": "@statelyai/graph",
        "url": "/docs/packages/graph"
      },
      {
        "title": "Adjacency List",
        "url": "/docs/packages/graph/src-formats-adjacency-list"
      },
      {
        "title": "Converter",
        "url": "/docs/packages/graph/src-formats-converter"
      },
      {
        "title": "Cytoscape",
        "url": "/docs/packages/graph/src-formats-cytoscape"
      },
      {
        "title": "D3",
        "url": "/docs/packages/graph/src-formats-d3"
      },
      {
        "title": "DOT",
        "url": "/docs/packages/graph/src-formats-dot"
      },
      {
        "title": "Edge List",
        "url": "/docs/packages/graph/src-formats-edge-list"
      },
      {
        "title": "ELK",
        "url": "/docs/packages/graph/src-formats-elk"
      },
      {
        "title": "GEXF",
        "url": "/docs/packages/graph/src-formats-gexf"
      },
      {
        "title": "GML",
        "url": "/docs/packages/graph/src-formats-gml"
      },
      {
        "title": "GraphML",
        "url": "/docs/packages/graph/src-formats-graphml"
      },
      {
        "title": "JGF",
        "url": "/docs/packages/graph/src-formats-jgf"
      },
      {
        "title": "Mermaid",
        "url": "/docs/packages/graph/src-formats-mermaid"
      },
      {
        "title": "TGF",
        "url": "/docs/packages/graph/src-formats-tgf"
      },
      {
        "title": "xyflow",
        "url": "/docs/packages/graph/src-formats-xyflow"
      }
    ]
  },
  {
    "name": "SDK",
    "package": "sdk",
    "pages": [
      {
        "title": "@statelyai/sdk",
        "url": "/docs/packages/sdk"
      }
    ]
  }
] as const;
